version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    groups:
      production-deps:
        dependency-type: production
      dev-deps:
        dependency-type: development
        update-types:
          - minor
          - patch
      typescript:
        patterns:
          - "typescript"
          - "ts-*"
          - "@types/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "postcss*"
          - "autoprefixer"
      vite:
        patterns:
          - "vite"
          - "vite-*"
          - "@vitejs/*"
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "playwright*"
          - "@playwright/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    groups:
      actions:
        patterns:
          - "*"
